language: node_js

node_js:
  - "8.11"

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install: yarn

script:
  - unset CI
  - yarn run gatsby-build

cache: npm

deploy:
  - provider: s3
    cache_control: "max-age=31536000"
    access_key_id: $aws_access_key_id
    secret_access_key: $aws_secret_access_key
    bucket: $prod_s3_bucket
    acl: public_read
    local_dir: packages/landing-gatsby/public
    skip_cleanup: true
    region: "eu-west-1"
    on:
      all_branches: true


after_deploy:
  - aws configure set aws_access_key_id $aws_access_key_id
  - aws configure set aws_secret_access_key $aws_secret_access_key
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DISTRIBUTION --paths "/*"