language: node_js

node_js:
  - "11"

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install -g ipfs-deploy

install: yarn

script:
  - unset CI
  - yarn run gatsby-build

cache: yarn

deploy:
  - provider: script
    script: ./scripts/update-route53.sh
    on:
      all_branches: true
